site_name: reproschema-py
nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
    - Introduction: user_guide/index.md
    - CLI Usage: user_guide/cli_usage.md
    - Reproschema to REDCap: user_guide/reproschema2redcap.md
    - REDCap to Reproschema: user_guide/redcap2reproschema.md
    - Output to REDCap: user_guide/output2redcap.md
    - Reproschema to FHIR: user_guide/reproschema2fhir.md
  - About: about.md

theme: readthedocs
