site_name: reporschema-py
nav:
  - Home: index.md
  - Installation: installation.md
  - CLI Usage: cli_usage.md
  - Converting from reproschema to redcap: reproschema2redcap.md
  - Converting from redcap to reproschema: redcap2reproschema.md
  - Converting the output into redcap: output2redcap.md
  - Converting the reproschema into an FHIR Questionnaire Resource: reproschema2fhir.md

theme: readthedocs
